<a href="https://colab.research.google.com/github/yuZuPluZ/Lab5/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015052 ชื่อ ธนพนธ์ ภูพานทอง :

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
from typing import Tuple
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  return True if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0 else False


def day_of_year(day, month, year):

  sum_day = 0
  if leap_year(year) == True:
     days_in_month[1] = 29
  if month < 1:
     return day
  else:
    for i in range(month - 1):
        sum_day += days_in_month[i]
  return sum_day + day







# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 61

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 167
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 91
30 Jun 2023: 182
30 Sep 2023: 274
31 Dec 2023: 366


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
from typing import Tuple
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  return True if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0 else False


def day_of_year(day, month, year):

  sum_day = 0
  if leap_year(year) == True:
     days_in_month[1] = 29
  else:
    days_in_month[1] = 28

  if month == 1:
     return day
  else:
    for i in range(month - 1):
        sum_day += days_in_month[i]

  return sum_day + day


def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
  day1,month1,year1 = map(int,date1.split("-"))
  day2,month2,year2 = map(int,date2.split("-"))
  day_of_year1 = day_of_year(day1,month1,year1)
  day_of_year2 = day_of_year(day2,month2,year2)

  if year1 == year2:
    return abs(day_of_year1 - day_of_year2) +1

  day_remain_of_year1 = (day_in_year(year1) - day_of_year1) +1
  day = 0
  for i in range(year1+1 , year2):
    day += day_in_year(i)
  total_day = (day_remain_of_year1 + day_of_year2 + day)
  return(day_in_year(year1),day_in_year(year2),total_day)



# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367   (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366   (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 366  (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)


(365, 366, 731)
(365, 366, 76)
(366, 365, 367)
(365, 365, 366)
(366, 365, 366)
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
from typing import Tuple
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  return True if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0 else False


def day_of_year(day, month, year):

  sum_day = 0
  if leap_year(year) == True:
     days_in_month[1] = 29
  else:
    days_in_month[1] = 28

  if month == 1:
     return day
  else:
    for i in range(month - 1):
        sum_day += days_in_month[i]

  return sum_day + day


def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
  try:
    day1,month1,year1 = map(int,date1.split("-"))
    day2,month2,year2 = map(int,date2.split("-"))
  except:
    return -1

  if month1 < 1 or month1 > 12 or month2 < 1 or month2 > 12 :
        return -1
  if day1 > days_in_month[month1 - 1] or day2 > days_in_month[month2 - 1] :
        return -1

  day_of_year1 = day_of_year(day1,month1,year1)
  day_of_year2 = day_of_year(day2,month2,year2)

  if year1 == year2:
    return abs(day_of_year1 - day_of_year2) +1

  day_remain_of_year1 = (day_in_year(year1) - day_of_year1) +1
  day = 0
  for i in range(year1+1 , year2):
    day += day_in_year(i)
  total_day = (day_remain_of_year1 + day_of_year2 + day)
  return(total_day)


# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)a
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 366 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# # ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [9]:

import math
def simulate_fish_population(n, p ,month=3):
  deadtime = 5*12
  months = 120
  round = month / 3
  monthcount = 0
  egg_fish = 0
  baby_fish = 0
  big_fish = 0
  fish_count_month = []
  for i in range(1 , months + 1):
    if monthcount >= deadtime:
      n -= fish_count_month[0]
      fish_count_month.pop(0)
    egg_fish = (n/2) * 300
    monthcount +=1

    if monthcount >= deadtime:
      n -= fish_count_month[0]
      fish_count_month.pop(0)
    fish_count_month.append(n)
    baby_fish += egg_fish - (egg_fish * p/100)
    egg_fish -= (n/2) * 300
    egg_fish += (n/2) * 300
    monthcount +=1

    if monthcount >= deadtime:
      n -= fish_count_month[0]
      fish_count_month.pop(0)
    fish_count_month.append(n)
    big_fish = baby_fish - (baby_fish * p/100)
    monthcount +=1
    t_fish = baby_fish+big_fish+n
    if month % months == 0:
            print(f"Month {monthcount}: Total fish = {int(t_fish)}")
    big_fish += n
    n = big_fish
    fish_count_month.append(n)

  return egg_fish ,baby_fish ,big_fish

month = 10 * 12
n = 2
p = 10

simulate_fish_population(n, p, month)




n = 2
p = 10

simulate_fish_population(n, p)


Month 3: Total fish = 515
Month 6: Total fish = 63600
Month 9: Total fish = 7854146
Month 12: Total fish = 969923523
Month 15: Total fish = 119777700959
Month 18: Total fish = 14791576144936
Month 21: Total fish = 1826639876198702
Month 24: Total fish = 225575233134394784
Month 27: Total fish = 27856714652221554688
Month 30: Total fish = 3440078684316227338240
Month 33: Total fish = 424821860798401947369472
Month 36: Total fish = 52462059729918318667104256
Month 39: Total fish = 6478639554784114728815820800
Month 42: Total fish = 800059522956108062793857499136
Month 45: Total fish = 98800872445524592535489814200320
Month 48: Total fish = 12201107687499327494352831552421888
Month 51: Total fish = 1506737998533721458754247279803105280
Month 54: Total fish = 186069941711227115622943933339191476224
Month 57: Total fish = 22978131063338014509885161602052146593792
Month 60: Total fish = 2837613116380532739158859717128374588538880
Month 63: Total fish = 350422241741932491186377539015155731709

(2.391100508441784e+251, 2.1695588879765659e+251, 1.968543669235188e+251)

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [ ]:
def find_mismatch(str1, str2):
    string1 = str1.lower()
    string2 = str2.lower()

    range_diff = abs(len(str1) - len(str2))

    if string1 == string2:
        return 0

    if range_diff == 1:
        if len(str1) < len(str2):
            shorter = string1
            longer = string2
        else:
            shorter = string2
            longer = string1

        for i in range(len(longer)):
            if shorter == longer[:i] + longer[i+1:]:
                return 1


    if len(str1) == len(str2):
        difference_count = 0
        for i in range(len(str1)):
            if string1[i] != string2[i]:
                difference_count += 1

            if difference_count > 1:
                return 2

        if difference_count == 1:
            return 1

    return 2

print(find_mismatch("Thes", "that"))
print(find_mismatch("book", "boot"))
print(find_mismatch("fan", "fun"))
print(find_mismatch("sin", "sink"))
print(find_mismatch("Dog", "dog"))
print(find_mismatch("poke", "spoke"))
print(find_mismatch("poker", "poke"))


2
1
1
1
0
1
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [ ]:
def find_mismatch(str1, str2):

    string1 = str1.lower()
    string2 = str2.lower()

    range_diff = abs(len(str1) - len(str2))

    if string1 == string2:
        return 0

    if range_diff == 1:
        if len(str1) < len(str2):
            shorter = string1
            longer = string2
        else:
            shorter = string2
            longer = string1

        for i in range(len(longer)):
            if shorter == longer[:i] + longer[i+1:]:
                return 1


    if len(str1) == len(str2):
        difference_count = 0
        for i in range(len(str1)):
            if string1[i] != string2[i]:
                difference_count += 1

            if difference_count > 1:
                return 2

        if difference_count == 1:
            return 1

    return 2
def isEnglish(input_string):
    try:
        input_string.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True

def spelling_correction(input_string, correct_spells):
  if not isEnglish(input_string):
        return "Error: Input contains non-English characters."
  input_str = input_string.strip().split()
  for i in range(len(input_str)):
    for j in range(len(correct_spells)):
      if find_mismatch(input_str[i], correct_spells[j]) == 1:
        input_str[i] = correct_spells[j]
  return " ".join(input_str)


print(spelling_correction("Thes is the Firs cas",["that","first","case","car"]))
print(spelling_correction("programming is fan and easy",["programming","this","fun","easy","book"]))
print(spelling_correction("Thes is vary essy",["this","is","very","easy"]))
print(spelling_correction("Wee ipve Pythen",["we","live","ln","Python"]))
print(spelling_correction("ฟกฟพ ipve Pythen",["we","live","ln","Python"]))

Thes is the first case
programming is fun and easy
this is very easy
we ipve Python
Error: Input contains non-English characters.


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [ ]:
crosswords = [['s', 'd', 'o', 'g'],
              ['c', 'u', 'c', 'm'],
              ['a', 'c', 'a', 't'],
              ['t', 'e', 't', 'k']]
word = 'cat'




def find_word_horizontal(crosswords, word):
    len_word = len(word)
    rows = len(crosswords)
    cols = len(crosswords[0])

    for row in range(rows):
      column_string = ''.join(crosswords[row][col] for col in range(cols))

      index = column_string.find(word)

      if index != -1:
          return [row, index]


    return None


print(find_word_horizontal(crosswords,word))

[1, 2]


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
crosswords = [['s', 'd', 'o', 'g'],
              ['c', 'u', 'c', 'm'],
              ['a', 'c', 'a', 't'],
              ['t', 'e', 't', 'k']]
word = 'cat'




def find_word_vertical(crosswords, word):
    len_word = len(word)
    rows = len(crosswords)
    cols = len(crosswords[0])
    for col in range(cols):
        column_string = ''.join(crosswords[row][col] for row in range(rows))


        index = column_string.find(word)

        if index != -1:
            return [index, col]



print(find_word_vertical(crosswords,word))


[1, 0]


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [ ]:
def find_word_horizontal(crosswords, word):
    len_word = len(word)
    rows = len(crosswords)
    cols = len(crosswords[0])

    for row in range(rows):
      column_string = ''.join(crosswords[row][col] for col in range(cols))

      index = column_string.find(word)

      if index != -1:
          return [row, index]


    return None


def find_word_vertical(crosswords, word):
    len_word = len(word)
    rows = len(crosswords)
    cols = len(crosswords[0])
    for col in range(cols):
        column_string = ''.join(crosswords[row][col] for row in range(rows))


        index = column_string.find(word)

        if index != -1:
            return [index, col]



def capitalize_word_in_crossword(crosswords, word):

    def capitalize_in_row(row_index, start_col):
        for i in range(len(word)):
            crosswords[row_index][start_col + i] = crosswords[row_index][start_col + i].upper()

    def capitalize_in_col(col_index, start_row):
        for i in range(len(word)):
            crosswords[start_row + i][col_index] = crosswords[start_row + i][col_index].upper()

    result = find_word_horizontal(crosswords, word)
    if result:
        row, col = result
        capitalize_in_row(row, col)
        return

    result = find_word_vertical(crosswords, word)
    if result:
        row, col = result
        capitalize_in_col(col, row)
        return

    return None

crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word = 'cat'

capitalize_word_in_crossword(crosswords, word)
for row in crosswords:
    print(' '.join(row))


s d o g
c u c m
a C A T
t e t k
